# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160417_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
